### ISSUE TITLE
Error coming from tools/sync_neon_event_to_db.php

### ISSUE THREAD

**Issue by tskeeley** [CON-In-A-Box/CIAB-Portal#594]
This isn't running - Do we need it still?  I assume so, but bow your your greater knowledge.

# /usr/bin/php /srv/www/htdocs/signin/tools/sync_neon_event_to_db.php
PHP Fatal error:  Uncaught Error: Call to a member function go() on null in /srv/www/htdocs/signin/tools/neon_event_lib.inc:32
Stack trace:
#0 /srv/www/htdocs/signin/tools/sync_neon_event_to_db.php(125): _loadEventCustomFields()
#1 /srv/www/htdocs/signin/tools/sync_neon_event_to_db.php(151): do_event_Neon_import()
#2 {main}
  thrown in /srv/www/htdocs/signin/tools/neon_event_lib.inc on line 32

**Comment by AricStewart** [comment]
oh yes, this is very broken and has been since Jul 2021... So being broken has not hurt us as far as we have realized for over a year.  But likely it would be good to fix.  I will try to figure out the best way to re-work these tools to use the new CRM framework.
